#!/bin/bash

echo "🚀 Kube Credential - Render Deployment Guide"
echo "=============================================="
echo ""

echo "📋 STEP 1: Deploy Issuance Service to Render"
echo "---------------------------------------------"
echo "1. Go to: https://dashboard.render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect GitHub repository"
echo "4. Configure:"
echo "   - Name: kube-credential-issuance"
echo "   - Environment: Docker"
echo "   - Dockerfile Path: backend/issuance-service/Dockerfile"
echo "   - Port: 3000"
echo "5. Environment Variables:"
echo "   - NODE_ENV=production"
echo "   - PORT=3000"
echo "   - HOSTNAME=render-issuance"
echo "6. Click 'Create Web Service'"
echo ""

echo "📋 STEP 2: Deploy Verification Service to Render"
echo "------------------------------------------------"
echo "1. Click 'New +' → 'Web Service'"
echo "2. Configure:"
echo "   - Name: kube-credential-verification"
echo "   - Environment: Docker"
echo "   - Dockerfile Path: backend/verification-service/Dockerfile"
echo "   - Port: 3001"
echo "3. Environment Variables:"
echo "   - NODE_ENV=production"
echo "   - PORT=3001"
echo "   - HOSTNAME=render-verification"
echo "   - VERIFICATION_SERVICE_URL=https://kube-credential-issuance.onrender.com"
echo "4. Click 'Create Web Service'"
echo ""

echo "📋 STEP 3: Deploy Frontend to Vercel"
echo "------------------------------------"
echo "1. Go to: https://vercel.com"
echo "2. Import project from GitHub"
echo "3. Configure:"
echo "   - Framework Preset: Vite"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: dist"
echo "4. Environment Variables:"
echo "   - VITE_ISSUANCE_SERVICE_URL=https://kube-credential-issuance.onrender.com"
echo "   - VITE_VERIFICATION_SERVICE_URL=https://kube-credential-verification.onrender.com"
echo "5. Deploy"
echo ""

echo "🔗 STEP 4: Test Complete Flow"
echo "-----------------------------"
echo "1. Wait for all services to deploy (5-10 minutes)"
echo "2. Test issuance:"
echo "   curl -X POST https://kube-credential-issuance.onrender.com/issue \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"id\":\"test-123\",\"name\":\"Test User\"}'"
echo ""
echo "3. Test verification:"
echo "   curl -X POST https://kube-credential-verification.onrender.com/verify \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"id\":\"test-123\"}'"
echo ""
echo "4. Access frontend at your Vercel URL"
echo ""

echo "✅ DEPLOYMENT COMPLETE!"
echo "======================"
echo "Frontend URL: https://your-app.vercel.app"
echo "Issuance API: https://kube-credential-issuance.onrender.com"
echo "Verification API: https://kube-credential-verification.onrender.com"
