version: '3.8'

services:
  issuance-service:
    build: ./backend/issuance-service
    container_name: issuance-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=issuance-docker
      - VERIFICATION_SERVICE_URL=http://verification-service:3001
    volumes:
      - issuance-data:/app/dist/data
    networks:
      - kube-credential-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  verification-service:
    build: ./backend/verification-service
    container_name: verification-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOSTNAME=verification-docker
    volumes:
      - verification-data:/app/dist/data
    networks:
      - kube-credential-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - VITE_ISSUANCE_SERVICE_URL=http://localhost:3000
      - VITE_VERIFICATION_SERVICE_URL=http://localhost:3001
    networks:
      - kube-credential-network
    depends_on:
      - issuance-service
      - verification-service

volumes:
  issuance-data:
  verification-data:

networks:
  kube-credential-network:
    driver: bridge