apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-deployment
  labels:
    app: verification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: verification
  template:
    metadata:
      labels:
        app: verification
    spec:
      containers:
      - name: verification
        image: kube-credential/verification-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VERIFICATION_SERVICE_URL
          value: "http://issuance-service:80"
        volumeMounts:
        - name: data
          mountPath: /app/dist/data
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: verification-service
spec:
  selector:
    app: verification
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP